In [ ]:
from itertools import product

# Define the target sum
target_sum = 100

# Create a list to store the permutations
permutations_list = []

# Generate all permutations of 5 numbers from 1 to 100 with replacement
# Opinions are all multiples of 5 to reduce the size of the population
counter = 0
for perm in product(range(0, 101, ), repeat=5):
    if sum(perm) == target_sum:
        permutations_list.append(perm)

# Print the list of the first 1000 permutations
permutations_list[0:1000]



In [ ]:
len(permutations_list)

[(0, 0, 0, 0, 100),
 (0, 0, 0, 1, 99),
 (0, 0, 0, 2, 98),
 (0, 0, 0, 3, 97),
 (0, 0, 0, 4, 96),
 (0, 0, 0, 5, 95),
 (0, 0, 0, 6, 94),
 (0, 0, 0, 7, 93),
 (0, 0, 0, 8, 92),
 (0, 0, 0, 9, 91),
 (0, 0, 0, 10, 90),
 (0, 0, 0, 11, 89),
 (0, 0, 0, 12, 88),
 (0, 0, 0, 13, 87),
 (0, 0, 0, 14, 86),
 (0, 0, 0, 15, 85),
 (0, 0, 0, 16, 84),
 (0, 0, 0, 17, 83),
 (0, 0, 0, 18, 82),
 (0, 0, 0, 19, 81),
 (0, 0, 0, 20, 80),
 (0, 0, 0, 21, 79),
 (0, 0, 0, 22, 78),
 (0, 0, 0, 23, 77),
 (0, 0, 0, 24, 76),
 (0, 0, 0, 25, 75),
 (0, 0, 0, 26, 74),
 (0, 0, 0, 27, 73),
 (0, 0, 0, 28, 72),
 (0, 0, 0, 29, 71),
 (0, 0, 0, 30, 70),
 (0, 0, 0, 31, 69),
 (0, 0, 0, 32, 68),
 (0, 0, 0, 33, 67),
 (0, 0, 0, 34, 66),
 (0, 0, 0, 35, 65),
 (0, 0, 0, 36, 64),
 (0, 0, 0, 37, 63),
 (0, 0, 0, 38, 62),
 (0, 0, 0, 39, 61),
 (0, 0, 0, 40, 60),
 (0, 0, 0, 41, 59),
 (0, 0, 0, 42, 58),
 (0, 0, 0, 43, 57),
 (0, 0, 0, 44, 56),
 (0, 0, 0, 45, 55),
 (0, 0, 0, 46, 54),
 (0, 0, 0, 47, 53),
 (0, 0, 0, 48, 52),
 (0, 0, 0, 49, 51),
 (0, 0, 0

In [16]:
len(valores)

4598126

In [ ]:
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
matplotlib.use("TkAgg")

# Create a figure and axis for the animation
fig, ax = plt.subplots()

# Function to update the histogram in each frame
def update(frame):
    ax.clear()
    data = permutations_list[frame]
    ax.bar([1,2,3,4,5],data, alpha=0.75)
    ax.set_title(f'Permutation {frame + 1}')
    ax.set_xlabel('Value')
    ax.set_ylabel('Frequency')
    ax.set_xlim(-0.5, 6)

# Create an animation object and assign it to a variable
ani = FuncAnimation(fig, update, frames=len(permutations_list), repeat=False)

# Display the animation



In [6]:
plt.show()

In [7]:
#Reduce the size of the population by implementing 
#Systematic Sampling by selecting every 15th element

filtered_list = []

for i in range(0,len(permutations_list)):
    if i%15 == 0:
        filtered_list.append(permutations_list[i])

In [8]:
len(filtered_list)

709

In [9]:
filtered_list

[(0, 0, 0, 0, 100),
 (0, 0, 0, 75, 25),
 (0, 0, 5, 45, 50),
 (0, 0, 10, 20, 70),
 (0, 0, 15, 0, 85),
 (0, 0, 15, 75, 10),
 (0, 0, 20, 60, 20),
 (0, 0, 25, 50, 25),
 (0, 0, 30, 45, 25),
 (0, 0, 35, 45, 20),
 (0, 0, 40, 50, 10),
 (0, 0, 50, 0, 50),
 (0, 0, 55, 20, 25),
 (0, 0, 65, 0, 35),
 (0, 0, 75, 0, 25),
 (0, 0, 90, 0, 10),
 (0, 5, 0, 45, 50),
 (0, 5, 5, 20, 70),
 (0, 5, 10, 0, 85),
 (0, 5, 10, 75, 10),
 (0, 5, 15, 60, 20),
 (0, 5, 20, 50, 25),
 (0, 5, 25, 45, 25),
 (0, 5, 30, 45, 20),
 (0, 5, 35, 50, 10),
 (0, 5, 45, 0, 50),
 (0, 5, 50, 20, 25),
 (0, 5, 60, 0, 35),
 (0, 5, 70, 0, 25),
 (0, 5, 85, 0, 10),
 (0, 10, 0, 45, 45),
 (0, 10, 5, 25, 60),
 (0, 10, 10, 10, 70),
 (0, 10, 15, 0, 75),
 (0, 10, 15, 75, 0),
 (0, 10, 20, 70, 0),
 (0, 10, 30, 0, 60),
 (0, 10, 35, 10, 45),
 (0, 10, 40, 25, 25),
 (0, 10, 45, 45, 0),
 (0, 10, 55, 25, 10),
 (0, 10, 65, 25, 0),
 (0, 10, 90, 0, 0),
 (0, 15, 0, 70, 15),
 (0, 15, 5, 55, 25),
 (0, 15, 10, 45, 30),
 (0, 15, 15, 40, 30),
 (0, 15, 20, 40, 25),
 

In [10]:
# Function to update the histogram in each frame
def update(frame):
    ax.clear()
    data = filtered_list[frame]
    ax.bar([1,2,3,4,5],data, alpha=0.75)
    ax.set_title(f'Permutation {frame + 1}')
    ax.set_xlabel('Value')
    ax.set_ylabel('Frequency')
    ax.set_xlim(-0.5, 6)

# Display the animation


fig, ax = plt.subplots()
ani = FuncAnimation(fig, update, frames=len(filtered_list), repeat=False)


In [11]:
plt.show()

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(filtered_list, columns=["1","2","3","4","5"])

In [14]:
df

1   2   3   4    5
0     0   0   0   0  100
1     0   0   0  75   25
2     0   0   5  45   50
3     0   0  10  20   70
4     0   0  15   0   85
..   ..  ..  ..  ..  ...
704  80   0   0  20    0
705  80   5   5   0   10
706  80  20   0   0    0
707  85   5   5   5    0
708  90  10   0   0    0

[709 rows x 5 columns]

In [15]:
import random


In [16]:
random.seed(1)
random_data = random.sample(permutations_list, 500)

random_data

[(5, 10, 5, 60, 20),
 (45, 0, 35, 5, 15),
 (0, 25, 25, 40, 10),
 (10, 25, 50, 15, 0),
 (5, 0, 50, 25, 20),
 (30, 30, 25, 5, 10),
 (25, 30, 5, 40, 0),
 (30, 5, 20, 5, 40),
 (20, 15, 10, 10, 45),
 (10, 0, 40, 20, 30),
 (0, 50, 30, 5, 15),
 (30, 20, 15, 15, 20),
 (0, 10, 5, 20, 65),
 (20, 25, 0, 0, 55),
 (25, 10, 40, 0, 25),
 (55, 0, 25, 5, 15),
 (0, 0, 5, 65, 30),
 (25, 25, 5, 30, 15),
 (10, 40, 0, 40, 10),
 (10, 10, 25, 5, 50),
 (50, 0, 40, 0, 10),
 (0, 65, 15, 10, 10),
 (15, 15, 45, 0, 25),
 (0, 10, 15, 30, 45),
 (0, 5, 40, 10, 45),
 (0, 5, 65, 15, 15),
 (40, 0, 30, 5, 25),
 (0, 0, 40, 50, 10),
 (20, 15, 20, 25, 20),
 (10, 5, 10, 60, 15),
 (25, 5, 10, 0, 60),
 (0, 10, 5, 75, 10),
 (35, 25, 0, 15, 25),
 (10, 5, 45, 25, 15),
 (25, 15, 30, 0, 30),
 (30, 30, 35, 0, 5),
 (40, 15, 5, 35, 5),
 (10, 10, 65, 15, 0),
 (15, 50, 0, 10, 25),
 (10, 10, 40, 10, 30),
 (10, 5, 25, 15, 45),
 (25, 50, 25, 0, 0),
 (15, 0, 35, 5, 45),
 (0, 5, 35, 10, 50),
 (25, 0, 20, 50, 5),
 (40, 20, 10, 15, 15),
 (75, 5

In [17]:
df = pd.DataFrame(random_data, columns=["1","2","3","4","5"])


In [23]:
df["5"].plot.hist(bins=5, alpha=0.5)
plt.show()

In [24]:
df

1   2   3   4   5
0     5  10   5  60  20
1    45   0  35   5  15
2     0  25  25  40  10
3    10  25  50  15   0
4     5   0  50  25  20
..   ..  ..  ..  ..  ..
495  30  30  20   0  20
496  30  10  20  40   0
497  10  10   0  75   5
498  25   0   0  20  55
499  15  35  10  20  20

[500 rows x 5 columns]

In [44]:
subset = [list(random_data[i]) for i in range(0,4)]

experiments_data = []

for i in subset:
    experiments_data.append(i+ ["M1"] +[random.randint(0,100)])
    experiments_data.append(i+ ["M2"] +[random.randint(0,100)])
    experiments_data.append(i+ ["M3"] +[random.randint(0,100)])
                    
                    

In [46]:
df = pd.DataFrame(experiments_data,columns=["1","2","3","4","5","Model","Polarization"])


In [47]:
df

1   2   3   4   5 Model  Polarization
0    5  10   5  60  20    M1            20
1    5  10   5  60  20    M2            65
2    5  10   5  60  20    M3            98
3   45   0  35   5  15    M1            26
4   45   0  35   5  15    M2            39
5   45   0  35   5  15    M3            38
6    0  25  25  40  10    M1            88
7    0  25  25  40  10    M2            38
8    0  25  25  40  10    M3            70
9   10  25  50  15   0    M1            47
10  10  25  50  15   0    M2            21
11  10  25  50  15   0    M3            89

In [122]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split

In [ ]:
X=df[["1","2","3","4","5"]]
y = df["Polarization"]

In [142]:
X=np.array(X)

In [143]:
X

array([[ 5, 10,  5, 60, 20],
       [ 5, 10,  5, 60, 20],
       [ 5, 10,  5, 60, 20],
       [45,  0, 35,  5, 15],
       [45,  0, 35,  5, 15],
       [45,  0, 35,  5, 15],
       [ 0, 25, 25, 40, 10],
       [ 0, 25, 25, 40, 10],
       [ 0, 25, 25, 40, 10],
       [10, 25, 50, 15,  0],
       [10, 25, 50, 15,  0],
       [10, 25, 50, 15,  0]])

In [145]:
y = np.array(y)
y

array([20, 65, 98, 26, 39, 38, 88, 38, 70, 47, 21, 89])

In [146]:
k = 2  # Choose the value of k (number of neighbors)
knn_regressor = KNeighborsRegressor(n_neighbors=k)
knn_regressor.fit(X, y)

KNeighborsRegressor(n_neighbors=2)

In [139]:
y_pred = knn_regressor.predict([[5,10,5,60,20]])

In [140]:
y_pred

array([42.5])

In [109]:
df

1   2   3   4   5 Model  Polarization
0    5  10   5  60  20    M1            20
1    5  10   5  60  20    M2            65
2    5  10   5  60  20    M3            98
3   45   0  35   5  15    M1            26
4   45   0  35   5  15    M2            39
5   45   0  35   5  15    M3            38
6    0  25  25  40  10    M1            88
7    0  25  25  40  10    M2            38
8    0  25  25  40  10    M3            70
9   10  25  50  15   0    M1            47
10  10  25  50  15   0    M2            21
11  10  25  50  15   0    M3            89

In [120]:
np.array(X)

array([[ 5, 10,  5, 60, 20],
       [ 5, 10,  5, 60, 20],
       [ 5, 10,  5, 60, 20],
       [45,  0, 35,  5, 15],
       [45,  0, 35,  5, 15],
       [45,  0, 35,  5, 15],
       [ 0, 25, 25, 40, 10],
       [ 0, 25, 25, 40, 10],
       [ 0, 25, 25, 40, 10],
       [10, 25, 50, 15,  0],
       [10, 25, 50, 15,  0],
       [10, 25, 50, 15,  0]])